### ISSUE TITLE
Jump to previous position command in the Tools menu of Citavi's PDF Viewer

### ISSUE THREAD

**Issue by nickbote** [lutz/JumpToLastPositionAfterActionExecutionAddon#2]
Hi there,

Thank you for the very useful Citavi add-on. I just installed it. The keyboard shortcut Alt + F3 works, but the command **Jump to previous position** in the Tools menu of Citavi's PDF Viewer does not appear.

The keyboard shortcut is great when I am working on my computer, but not so helpful when I am reading on a tablet. Is there a way to add the Jump to previous position command in the Tools menu of Citavi's PDF Viewer?

By the way, I use Citavi 6.7.0.0.

Thank you in advance for your help,
NB

**Comment by lutz** [comment]
Hi nickbote,

thanks for posting. I will look into the code in the next days and come back to inform you about the next steps.

Best regards
Daniel

**Comment by nickbote** [comment]
Great, thank you for the prompt reply and willingness to help.

Look forward to hearing from you in the next days.

**Comment by lutz** [comment]
Hey nickbote,

can you clarify what exactly you mean? I test the addon with **Citavi 6.7**.

1. Open an pdf in the PDF viewer
2. Click on a link (jump to the next page)
3. The <kbd>Tools</kbd> menu contains the command <kbd>Jump to previous position...</kbd>

![09-12-_2020_08-10-51](https://user-images.githubusercontent.com/26437097/101597097-80c40480-39f6-11eb-9afc-51e9357f1b05.gif)

**Comment by nickbote** [comment]
Thank you very much Daniel, it works. I am not sure why I could not
see the Jump
to previous position command initially.

Thank you again,
Nikolai

**Comment by lutz** [comment]
Hello Nikolai,

the command is only visible if you had done a jump. If you open a pdf in the Viewer the command is not visible until you do your first jump.

I can change this behaviour for Citavi 6.7 that the command will be always visible but disabled until you do your first jump. You can look on the release page. I will change it in the next days.

Best regards
Daniel

**Comment by lutz** [comment]
[Version 1.0.1](https://github.com/lutz/JumpToLastPositionAfterActionExecutionAddon/releases/tag/v1.0.1)

**Comment by nickbote** [comment]
Dear Daniel,

Thank you again for the very useful Citavi addon and for helping with it. I
just upgraded to Citavi 6.8. Similar to other users Citavi started to crash
when opening a project. When I deactivated
"JumpToLastPositionAfterActionExecutionAddon", Citavi 6.8 started to work
normally.

Is there an easy way to continue using the addon under Citavi 6.8?

Thank you in advance,
Nikolai Botev

**Comment by lutz** [comment]
Please notice issue #4.

**Comment by nickbote** [comment]
Dear Daniel,

Hope you enjoyed your paternal leave. Have you had a chance to update the
addon for Citavi 6.8?

Thank you again for all your help,
Nikolai

**Comment by lutz** [comment]
Please notice this [issue](https://github.com/lutz/JumpToLastPositionAfterActionExecutionAddon/issues/4).

**Comment by nickbote** [comment]
Thank you so much.
